%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/yaoruini/Downloads/MDM3-House/Education, Health, Entertainment by local district.xlsx
%    Worksheet: Table 1
%
% Auto-generated by MATLAB on 18-Mar-2022 10:39:43

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = "Table 1";
opts.DataRange = "A2:F316";

% Specify column names and types
opts.VariableNames = ["LocalAuthorityCode", "LocalAuthority", "Retail", "Education", "Health", "ArtsEntertainmentRecreationOtherServices"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["LocalAuthorityCode", "LocalAuthority"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["LocalAuthorityCode", "LocalAuthority"], "EmptyFieldRule", "auto");

% Import the data
EducationHealthEntertainmentbylocaldistrict1 = readtable("/Users/yaoruini/Downloads/MDM3-House/Education, Health, Entertainment by local district.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts